cluster_properties = ['id',
                      'name',
                      'description',
                      'location',
                      'type',
                      'so',
                      'defaultNamespace',
                      'restAPIEndPoint',
                      'ip',
                      'connectionToken',
                      'slaLiteEndPoint',
                      'prometheusPushgatewayEndPoint',
                      'prometheusEndPoint',
                      'architecture',
                      'version']
